name: Farmer
author: Geik, Amowny, WaterArchery, hyperion, rudde, mehmet-27
main: xyz.geik.farmer.Main
version: v6-b106
api-version: 1.13
depend: [PlaceholderAPI]
softdepend: [Vault, RoyaleEconomy, PlayerPoints, GrinGotts, ElementalGems, ASkyBlock, BentoBox, SuperiorSkyblock2, GriefPrevention, FabledSkyBlock, Lands, ShopGUIPlus]
loadbefore: [AutoPickup]
commands:
  farmer:
    description: Main command of farmer
    aliases: [farm, çiftçi, fm, ciftci]